theme: jekyll-theme-minimal
title: Veille technologique
description: Ce site réunit des articles et des tutoriels autour du développement web et Android. Ce book est en évolution et s'enrichira au fil de l'eau.
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
